application: project2-972
version: 1
runtime: php55
api_version: 1
threadsafe: false
instance_class: F1
automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: 7
  min_pending_latency: 11ms
  max_pending_latency: 12ms

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.php
  
- url: /main.php
  script: main.php

- url: /upload.php
  script: upload.php
  
- url: /comments.php
  script: comments.php


- url: /login.php
  script: login.php
  
- url: /delete.php
  script: delete.php

- url: /upload_handler.php
  script: upload_handler.php
  

